In [7]:
import torch
import torch.nn as nn

In [8]:
randint = torch.randint(-100, 100, (6,))



In [9]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [10]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
input = torch.empty(2, 3)
input

tensor([[5.8589e+31, 3.5076e-41, 2.6863e+37],
        [4.1771e-41, 8.9029e+35, 4.1771e-41]])

In [13]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [14]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [15]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [16]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [19]:
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.80f}')

0.00007891654968261718750000000000000000000000000000000000000000000000000000000000


In [20]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

0.00047278
CPU times: user 458 μs, sys: 108 μs, total: 566 μs
Wall time: 797 μs


using the time library to record execution time %%time to record the time taken for the cell to execute

In [21]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device=device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device=device)

np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

0.02826381
0.08839488


In [22]:
# Define a probability tensor
probs = torch.tensor([0.1, 0.9])

# 10% or 0.1 => 0, 90% or 0.9 => 1. each probs points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution 
samples = torch.multinomial(probs, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [23]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [24]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [25]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [26]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [27]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [28]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [29]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# Stack the tensor along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([-4.8943, -6.1057,  2.8632], grad_fn=<SqueezeBackward4>)


In [31]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

#https://youtu.be/UU1WVnMk4E8?si=F6McV1oYrlLG6BZS&t=4109

tensor([0.0900, 0.2447, 0.6652])


In [32]:
# Initialize an embedding layer
embedding_dim = 100
vocabulary_size = 10000
embedding = nn.Embedding(vocabulary_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1,5,3,2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensiońality of the embedding vectors
print(embedded_output.shape)

torch.Size([4, 100])


In [33]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [34]:
int_64 = torch.randint(1, (3,2)).float() # .float() has rounding but converts int => float
# type int64
float_32 = torch.rand(2,3)
#type float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [36]:
a = torch.rand(2,3,5)
print(a.shape)
x, y, z = a.shape       # Unpacking dimensions
a = a.view(x,y,z)       # Make that tensor with the same dimensions
print(x,y,z)            # Print the dimensions
print(a.shape)

torch.Size([2,3,5])

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


torch.Size([2, 3, 5])